// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS2_Eb0geaqBaM6nF0HZ8zW4d5IMBdWj0',
    appId: '1:522720554843:web:7f92194ac62ef8d9b4347e',
    messagingSenderId: '522720554843',
    projectId: 'havershine',
    authDomain: 'havershine.firebaseapp.com',
    storageBucket: 'havershine.appspot.com',
    measurementId: 'G-MMHELBV9XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7PabprjPjyc0XzjXr8B6MoP28BoyGyMY',
    appId: '1:522720554843:android:c44ee61c1a73b96fb4347e',
    messagingSenderId: '522720554843',
    projectId: 'havershine',
    storageBucket: 'havershine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrIClrIl1QKvQhgUhxlpEeiKmYsxCaFxI',
    appId: '1:522720554843:ios:4480ee4a27947697b4347e',
    messagingSenderId: '522720554843',
    projectId: 'havershine',
    storageBucket: 'havershine.appspot.com',
    iosClientId: '522720554843-btvfc3thss4em4h0slvafrd2rgg6f3lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.algorithmEmpl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrIClrIl1QKvQhgUhxlpEeiKmYsxCaFxI',
    appId: '1:522720554843:ios:2caf82961f896306b4347e',
    messagingSenderId: '522720554843',
    projectId: 'havershine',
    storageBucket: 'havershine.appspot.com',
    iosClientId: '522720554843-jbn6iqacpeupeulvrgv30164b0mrsr7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.algorithmEmpl.RunnerTests',
  );
}
